var CardsText = ['a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg',
'a','b','c','dd','efef','fff','ggggg'
];
